
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "(.*).pem"
      - id: mixed-line-ending
        exclude: "(.*).pem"
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint
        args: ['-r ~MD013']

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: remove-tabs

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: clippy
        args: ['--', '-A test-attr-in-doctest']

  - repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.9
    hooks:
      - id: cargo-sort

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --color always
        language: system
        pass_filenames: false
